# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Maxcraft\DefaultBundle\Entity\User:
          algorithm: sha1
          encode_as_base64: false
          iterations: 1

    providers:
          users:
            entity: {class: MaxcraftDefaultBundle:User, property: username}

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER, ROLE_MODO
            ROLE_MODO: ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false

            secured_area:
                remember_me:
                    key: "qfezmoaufqszolnm"
                    lifetime: 31536000
                    path: /
                    domain: ~
                http_basic: ~
                pattern: ^/
                anonymous: ~
                form_login:
                    login_path: /
                    check_path: /login_check
                logout:
                    path: /logout
                    target: /
                #anonymous: ~
                #http_basic:
                #    realm: "Secured Demo Area"

