<?php

namespace Maxcraft\DefaultBundle\Entity;

/**
 * FactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactionRepository extends \Doctrine\ORM\EntityRepository
{
}
