<?php

namespace Maxcraft\DefaultBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

    public function findByPage($page, $parpage){
        return $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:News')->findBy(
            array('display' => 'true'),
            array('date' => 'desc'),
            ($page-1)*$parpage,
            $parpage
        );
    }

    public function countDisplay(){
        $totalNews =  $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:News')->findBy(
          array('display'=>'true'),
          null,
          null,
          0
        );

        return count($totalNews);
    }

    public function getComments(News $newsId){
        return $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:News')->findBy(
          array('news'=> $newsId),
          array('date' => 'desc'),
          null,
          0
        );
    }
}
