<?php

namespace Maxcraft\DefaultBundle\Entity;

/**
 * OnSaleZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnSaleZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
