<?php

namespace Maxcraft\DefaultBundle\Entity;

/**
 * PermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermsRepository extends \Doctrine\ORM\EntityRepository
{
}
