<?php

namespace Maxcraft\DefaultBundle\Entity;

/**
 * RentZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
