<?php

namespace Maxcraft\DefaultBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findWebZones($user){
        $webZones = array();
        $servZones = $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:Zone')->findBy(
            array('owner' => $user),
            null,
            null,
            0
        );
        foreach($servZones as $z){
            $webZones[] = $z;
        }

        return $webZones;
    }


}
